### ISSUE TITLE
I need to work on the bison model

### ISSUE THREAD

**Issue by Sunconure11** [ljfa-ag/Totemic#5]
Nothing to be said here, I have been slacking off until now. I'll do the model, and convert it to a usable format if needed. I'll likely texture it too.

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/6mz1pft4jkcdi0h/Screenshot%202015-04-25%2004.48.32.png?dl=0

WIP, using other bison models that have been made as aids to help me model this.

**Comment by Sunconure11** [comment]
I'll probably create bison meat as a possible drop, as well as some of the other items if possible.

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/ad54jkomi35wa14/Screenshot%202015-04-25%2006.15.43.png?dl=0

Almost there, just need to set up the texture map, and texture it. Then send over the model.

**Comment by Sunconure11** [comment]
I am unable to texture it today, but, the texture map will be started tomorrow. Since I think this branch will probably end up dying to the user picking it up claiming they are not suited for it, I probably won't do much more aside from a few item textures.

**Comment by ljfa-ag** [comment]
Yeah, sorry for that.
That screenshot looks pretty nice. Not sure if anyone is going to use it anywhere though

**Comment by Sunconure11** [comment]
I am near the verge of fixing my sleep schedule, which has been bothering me for the past few weeks. I will texture the model soon, its pretty much done, aside from a texture map. However, I doubt it will see use, but, I will send it over anyways when it is finished.

**Comment by Sunconure11** [comment]
Holy fuck I keep forgetting to texture this x.x

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/ki4pqaermtc221f/Screenshot%202015-09-25%2008.25.23.png?dl=0

I'm working on fixing the texture map.

**Comment by Sunconure11** [comment]
I fixed the bison's texture map.

https://www.dropbox.com/s/4k7desmvft5igfr/bison.tcn?dl=0

**Comment by ljfa-ag** [comment]
Great, thanks!

**Comment by ljfa-ag** [comment]
https://pbs.twimg.com/media/CP2rl4DW8AII2Oc.png:large
Okay, so that works now. All I need is a texture now. You didn't already give me one did you?

**Comment by Sunconure11** [comment]
I have not made one yet.

**Comment by Sunconure11** [comment]
If you want, I can make it later on. I might tweak the model slightly so it has a muzzle.

**Comment by Sunconure11** [comment]
Also, if the Afrit is going back in game, I'll probably model it.

I'm not going to do the texture today, but, I will do it. I also need to start on the still for Growthcraft.

**Comment by ljfa-ag** [comment]
Apparently not. But I'm probably not going to make it functional just yet.

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/scimfbzdidp9y85/Screenshot%202015-09-27%2011.23.23.png?dl=0

So it begins.

**Comment by Sunconure11** [comment]
Since I won't add a muzzle, I'll make the face somewhat similar to the vanilla cow. Plus it seems you did have a hard time porting the model over.

**Comment by ljfa-ag** [comment]
Well it wasn't that bad. It's just that I never used models before and I needed to figure out how the rotations work.

**Comment by Sunconure11** [comment]
Okay. Also, there was a minor error in the texture map, which I fixed.

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/sh7lwabpp2bfs4p/Screenshot%202015-09-27%2012.18.33.png?dl=0

What do you think of this so far?

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/d94o5q3ixxyq7s2/Screenshot%202015-09-27%2012.54.42.png?dl=0

Head and horns are finished for the most part. I'll work on the body later today.

**Comment by ljfa-ag** [comment]
Looks good to me

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/r57e6z6swf3lt1s/Screenshot%202015-09-27%2013.38.25.png?dl=0

Image used for reference: https://upload.wikimedia.org/wikipedia/commons/8/8d/American_bison_k5680-1.jpg

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/mzkipcdzgj8ney7/Screenshot%202015-09-27%2014.00.32.png?dl=0

Almost finished.

**Comment by Sunconure11** [comment]
It was faster than I thought.

https://www.dropbox.com/s/jzitikwt7kmssbo/bison.zip?dl=0

Also, I fixed the texture map, so, you will need to change the model again. There was an issue with one of the legs.

**Comment by ljfa-ag** [comment]
![2015-09-28_14 11 58](https://cloud.githubusercontent.com/assets/3437174/10135041/f834a8f2-65ea-11e5-9cbb-5f73490d39d7.png)
Great, so that works now. Thanks for your effort!
